/* 
    Created on : 10.07.2021, 13:18:59
    Author     : Andy Kar
*/

export const FETCH_INIT_INFO_START = 'FETCH_INIT_INFO_START'
export const FETCH_INIT_INFO_SUCCESS = 'FETCH_INIT_INFO_SUCCESS'
export const FETCH_INIT_INFO_ERROR = 'FETCH_INIT_INFO_ERROR'

export const FETCH_SESSION_START = 'FETCH_SESSION_START'
export const FETCH_SESSION_SUCCESS = 'FETCH_SESSION_SUCCESS'
export const FETCH_SESSION_ERROR = 'FETCH_SESSION_ERROR'

export const FETCH_ACCOUNT_INFO_START = 'FETCH_ACCOUNT_INFO_START'
export const FETCH_ACCOUNT_INFO_SUCCESS = 'FETCH_ACCOUNT_INFO_SUCCESS'
export const FETCH_ACCOUNT_INFO_ERROR = 'FETCH_ACCOUNT_INFO_ERROR'
export const FETCH_ACCOUNT_EDIT_START = 'FETCH_ACCOUNT_EDIT_START'
export const FETCH_ACCOUNT_EDIT_SUCCESS = 'FETCH_ACCOUNT_EDIT_SUCCESS'
export const FETCH_ACCOUNT_EDIT_ERROR = 'FETCH_ACCOUNT_EDIT_ERROR'

export const FETCH_CONTACTS_START = 'FETCH_CONTACTS_START'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR'
export const SEND_NEW_CONTACT_START = 'SEND_NEW_CONTACT_START'
export const SEND_NEW_CONTACT_ERROR = 'SEND_NEW_CONTACT_ERROR'
export const SEND_CONTACT_START = 'SEND_CONTACT_START'
export const SEND_CONTACT_ERROR = 'SEND_CONTACT_ERROR'
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS'


export const FETCH_CHECK_LOGGED_START = 'FETCH_CHECK_LOGGED_START'
export const FETCH_CHECK_LOGGED_SUCCESS = 'FETCH_CHECK_LOGGED_SUCCESS'
export const FETCH_CHECK_LOGGED_ERROR = 'FETCH_CHECK_LOGGED_ERROR'
export const SEND_LOGIN_INFO_START = 'SEND_LOGIN_INFO_START'
export const SEND_LOGIN_INFO_SUCCESS = 'SEND_LOGIN_INFO_SUCCESS'
export const SEND_LOGIN_INFO_ERROR = 'SEND_LOGIN_INFO_ERROR'
export const SEND_RESET_START = 'SEND_RESET_START'
export const SEND_RESET_SUCCESS = 'SEND_RESET_SUCCESS'
export const SEND_RESET_ERROR = 'SEND_RESET_ERROR'